version: '2.1'

volumes:
  ipython_history: {}

services:
  # ################################################################################
  # Database
  # ################################################################################
  postgres:
    image: mdillon/postgis
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=music_store_exercise_dev
      - POSTGRES_USER=music_store_exercise_user
      - POSTGRES_PASSWORD=manager

  # ################################################################################
  # Caching
  # ################################################################################
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"

  # ################################################################################
  # Queue broker for Celery
  # ################################################################################
  rabbitmq:
    image: rabbitmq:3.6.5
    ports:
      - "5672:5672"

  # ################################################################################
  # Abstraction
  # ################################################################################
  web_base:
    build: .
    volumes:
      - ./:/home/www/app
      - ipython_history:/root/.ipython/profile_default
    env_file:
    - .env
    command: echo 'Shutting down...'

  # ################################################################################
  # Celery scheduler
  # ################################################################################
  celery_beat:
    extends: web_base
    command: celery beat --app config.celery:app -l info -S django
    depends_on:
      - celery_worker
      - postgres
      - redis
      - rabbitmq
    links:
      - postgres
      - redis
      - rabbitmq

  # ################################################################################
  # Celery worker running async tasks
  # ################################################################################
  celery_worker:
    extends: web_base
    command: celery worker --app config.celery:app -l info
    depends_on:
      - postgres
      - redis
      - rabbitmq
    links:
      - postgres
      - redis
      - rabbitmq

  # ################################################################################
  # Celery monitoring tool
  # ################################################################################
  celery_flower:
    extends: web_base
    command: celery flower --app config.celery:app
    links:
      - rabbitmq
    ports:
      - "5555:5555"

  # ################################################################################
  # Django Backend / API
  # ################################################################################
  web:
    extends: web_base
    ports:
      - "8000:8000"
    command: python3 manage.py runserver_plus 0.0.0.0:8000 --reloader-type stat --pm
    entrypoint: .docker/docker-entrypoint.sh postgres
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
      - rabbitmq

  # ################################################################################
  # Documentation
  # ################################################################################
  sphinx:
    extends: web_base
    ports:
      - "8001:8001"
    command: sphinx-autobuild docs .dev/sphinx-docs -H 0.0.0.0 -p 8001
    environment:
      - APP_ENV=local


  # ################################################################################
  # Swagger API UI
  # ################################################################################
  swagger:
    # you can find definition of this image here:
    # https://gitblit.saritasa.com/summary/?r=~vladimirkasatkin/docker/swagger-ui-local.git
    image: docker.saritasa.com/swagger-ui-local:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./artifacts/:/home/www/swaggers
      - ./docs/swagger/:/src/swagger




