# Django Storages S3
AWS_S3_ACCESS_KEY_ID = '%AWS_S3_ACCESS_KEY_ID%'
AWS_S3_SECRET_ACCESS_KEY = '%AWS_S3_SECRET_ACCESS_KEY%'
AWS_S3_ENDPOINT_URL = '%AWS_S3_ENDPOINT_URL%'
AWS_STORAGE_BUCKET_NAME = '%AWS_STORAGE_BUCKET_NAME%'

# Django Storages
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_SECURE_URLS = False
AWS_QUERYSTRING_AUTH = False
