# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_location_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='balance'),
        ),
    ]
