# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_location_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PaymentMethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'Payment transaction',
                'verbose_name_plural': 'Payment transactions',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='default_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_by_default', to='users.PaymentMethod', verbose_name='default method'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='methods_used',
            field=models.ManyToManyField(related_name='users', to='users.PaymentMethod', verbose_name='methods used'),
        ),
    ]
