# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180409_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='default_method',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='methods_used',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
