# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180409_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='default_method',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='methods_used',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
