# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180411_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
