# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180406_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Payment transaction', 'verbose_name_plural': 'Payment transactions'},
        ),
    ]
