# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180406_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
