# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180406_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment method', 'verbose_name_plural': 'Payment methods'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='default_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_by_default', to='users.PaymentMethod', verbose_name='default method'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='methods_used',
            field=models.ManyToManyField(related_name='users', to='users.PaymentMethod', verbose_name='methods used'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.BigIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PaymentMethod', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
