# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-06 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='boughtalbum',
            options={'verbose_name': 'Bought album', 'verbose_name_plural': 'Bought albums'},
        ),
        migrations.AlterModelOptions(
            name='boughttrack',
            options={'verbose_name': 'Bought track', 'verbose_name_plural': 'Bought tracks'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='boughtalbum',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='boughtalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='boughttrack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.Track', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='boughttrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='track',
            name='price',
            field=models.BigIntegerField(default=1.0, verbose_name='price'),
        ),
        migrations.AlterUniqueTogether(
            name='boughtalbum',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='boughttrack',
            unique_together=set([]),
        ),
    ]
