# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boughtalbum',
            unique_together=set([('user', 'item')]),
        ),
        migrations.AlterUniqueTogether(
            name='boughttrack',
            unique_together=set([('user', 'item')]),
        ),
    ]
