# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.MusicTrack'),
        ),
        migrations.AlterField(
            model_name='liketrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='liketrack',
            unique_together=set([('track', 'user')]),
        ),
    ]
