# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_name',
            new_name='title',
        ),
    ]
