# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_store', '0002_auto_20180413_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bought_users',
            field=models.ManyToManyField(related_name='albums', through='music_store.BoughtAlbum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='bought_users',
            field=models.ManyToManyField(related_name='tracks', through='music_store.BoughtTrack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boughtalbum',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='music_store.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='boughttrack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='music_store.Track', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='liketrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User liked'),
        ),
    ]
