# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_store', '0002_auto_20180412_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bought_users',
            field=models.ManyToManyField(related_name='albums', through='music_store.BoughtAlbum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='bought_users',
            field=models.ManyToManyField(related_name='tracks', through='music_store.BoughtTrack', to=settings.AUTH_USER_MODEL),
        ),
    ]
