# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 06:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0002_auto_20180404_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='boughttrack',
            name='date_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
