# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0002_auto_20180409_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='track',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author'),
        ),
    ]
