# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 04:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0002_auto_20180413_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('created',), 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('created',), 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(max_length=200, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='boughtalbum',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='music_store.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='boughttrack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='music_store.Track', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='liketrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.Track', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='liketrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='liked by'),
        ),
        migrations.AlterField(
            model_name='listentrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.Track', verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='listentrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='listened by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_store.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='track',
            name='free_version',
            field=models.TextField(default='free version', verbose_name='free version'),
        ),
        migrations.AlterField(
            model_name='track',
            name='full_version',
            field=models.TextField(verbose_name='full version'),
        ),
        migrations.AlterField(
            model_name='track',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
