# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0003_auto_20180404_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_name',
            field=models.CharField(default='Undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='track_price',
            field=models.FloatField(default=1.0),
        ),
    ]
