# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0003_auto_20180411_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Liked by'),
        ),
        migrations.AlterField(
            model_name='listentrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Listened by'),
        ),
    ]
