# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0004_auto_20180419_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
