# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0005_auto_20180510_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='free_version',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='free version'),
        ),
        migrations.AlterField(
            model_name='track',
            name='full_version',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='full version'),
        ),
    ]
