# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0005_auto_20180405_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_name',
            new_name='title',
        ),
    ]
